Five floor
SoftServeSAG/robotics_spot pull request #10
Opened 2020-11-03 15:32 UTC by tarasborov

The fifth floor with stairs was added to the simulation world.

2020-11-05 15:52 UTC, ldemk requested changes

2020-11-05 15:52 UTC, ldemk commented on rs_gazebo/launch/HQ.launch
> +  <!-- <arg name="world_name" default="empty.world" /> -->
remove unnecessary comments

2020-11-05 15:52 UTC, ldemk commented on rs_gazebo/models/ss_hq4/stairs_45/model.config
> +    </author>
add your email and yourself as author

2020-11-05 15:52 UTC, ldemk commented on rs_gazebo/models/ss_hq4/stairs_45/model.sdf
> +  <model name='Untitled'>
Add some meaningful title to the model

2020-11-05 15:52 UTC, ldemk commented on rs_gazebo/worlds/ss_hq4and5.world
> +              <uri>file://media/materials/scripts/gazebo.material</uri>
Are you sire it will work with absolute path?

2020-11-05 15:52 UTC, ldemk commented on rs_gazebo/worlds/stairs_only.world
> +      <!--<direction>-0.5 0.1 -0.9</direction>-->
Remove the comments if they are not needed

2020-11-05 15:52 UTC, ldemk commented on rs_gazebo/worlds/stairs_only.world
> +  <world name='default'>
Change the name to meaningful title

2020-11-05 15:52 UTC, ldemk commented on rs_inverse/scripts/env_tester.py
>  def callback_model(data):
Much better is to make it a part of the class and then you might omit the global variables declaration

2020-11-09 13:29 UTC, tarasborov commented on rs_gazebo/launch/HQ.launch
> +  <!-- <arg name="world_name" default="empty.world" /> -->
Done in 89ad8b4f29d0c4017397ebd86242b846ef349683

2020-11-09 13:32 UTC, tarasborov commented on rs_gazebo/models/ss_hq4/stairs_45/model.sdf
> +  <model name='Untitled'>
Done in aeeefd33c02f0487cc1a09a8ad16bda8167f326c

2020-11-09 13:38 UTC, tarasborov commented on rs_inverse/scripts/env_tester.py
>  def callback_model(data):
It was done in newer branch

2020-11-09 13:38 UTC, tarasborov reviewed
Done

2020-11-09 13:42 UTC, tarasborov commented on rs_gazebo/worlds/stairs_only.world
> +  <world name='default'>
Done in ee04ad38f434ebae9fed92d10aa76bd8890ce770

2020-11-09 13:44 UTC, tarasborov commented on rs_gazebo/models/ss_hq4/stairs_45/model.config
> +    </author>
Done in aeeefd33c02f0487cc1a09a8ad16bda8167f326c

2020-11-09 13:50 UTC, tarasborov reviewed
Have done

2020-11-09 13:52 UTC, tarasborov commented on rs_gazebo/worlds/stairs_only.world
> +      <!--<direction>-0.5 0.1 -0.9</direction>-->
Done

2020-11-09 13:56 UTC, tarasborov commented on rs_gazebo/worlds/ss_hq4and5.world
> +              <uri>file://media/materials/scripts/gazebo.material</uri>
It works. This was in origin file ss_hq4

2020-11-12 16:18 UTC, ldemk approved these changes

2020-11-12 16:18 UTC, merged